name: Release HaikuPorter Buildmaster
on: workflow_dispatch
#on:
#  release:
#    types: [published]
jobs:
  build:
    env:
      REPOSITORY: "ghcr.io/haikuporter"
    name: Build HaikuPorter Buildmaster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Detect version
      id: detect-version
      run: echo "RELEASE_VERSION=$(git describe --dirty --tags --abbrev=1)" >> "$GITHUB_OUTPUT"
    - name: List version
      run: echo "Building ${{ steps.detect-version.outputs.RELEASE_VERSION }}..."
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push multi-architecture backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: buildmaster/backend/Dockerfile
        push: true
        tags: |
          ${{env.REPOSITORY}}/buildmaster:${{ steps.detect-version.outputs.RELEASE_VERSION }}-amd64
          ${{env.REPOSITORY}}/buildmaster:${{ steps.detect-version.outputs.RELEASE_VERSION }}-arm64
        platforms: linux/amd64,linux/arm64
    - uses: int128/docker-manifest-create-action@v2
      with:
        tags: ${{env.REPOSITORY}}/buildmaster:${{ steps.detect-version.outputs.RELEASE_VERSION }}
        sources: |
          ${{env.REPOSITORY}}/buildmaster:${{ steps.detect-version.outputs.RELEASE_VERSION }}-amd64
          ${{env.REPOSITORY}}/buildmaster:${{ steps.detect-version.outputs.RELEASE_VERSION }}-arm64
    - name: Build and push multi-architecture frontend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: buildmaster/frontend/Dockerfile
        push: true
        tags: |
          ${{env.REPOSITORY}}/frontend:${{ steps.detect-version.outputs.RELEASE_VERSION }}-amd64
          ${{env.REPOSITORY}}/frontend:${{ steps.detect-version.outputs.RELEASE_VERSION }}-arm64
        platforms: linux/amd64,linux/arm64
    - uses: int128/docker-manifest-create-action@v2
      with:
        tags: ${{env.REPOSITORY}}/frontend:${{ steps.detect-version.outputs.RELEASE_VERSION }}
        sources: |
          ${{env.REPOSITORY}}/frontend:${{ steps.detect-version.outputs.RELEASE_VERSION }}-amd64
          ${{env.REPOSITORY}}/frontend:${{ steps.detect-version.outputs.RELEASE_VERSION }}-arm64
